# ANSIBLE_SSH_ARGS="-o StrictHostKeyChecking=no" ansible-playbook -i <ip_addr>, ansible.yaml --ask-pass
---
- name: Updating the system
  hosts: all
  gather_facts: true
  become: true
  vars:
    ansible_user: adminuser
  tasks:
    - name: Perform a dist-upgrade
      ansible.builtin.apt:
        upgrade: dist
        update_cache: true
    - name: Check if a reboot is required
      ansible.builtin.stat:
        path: /var/run/reboot-required
        get_checksum: false
      register: reboot_required_file
    - name: Reboot the server
      ansible.builtin.reboot:
        reboot_timeout: 600
      when: reboot_required_file.stat.exists == true
    - name  : Remove dependencies that are no longer required
      ansible.builtin.apt:
        autoremove: true
    - name: Git Clone
      git:
        repo: https://github.com/ewancoder/exadel-report-hub.git
        dest: /exadel/
    - name: Git Checkout
      git:
        repo: /exadel/
        dest: /exadel/
        version: ForHosting 
    
- name: Installing Docker
  hosts: all
  gather_facts: true
  become: true
  roles:
    - geerlingguy.docker
  vars:
    ansible_user: adminuser
  tasks: 
    - name: Docker compose up
      community.docker.docker_compose_v2:
        project_src: /exadel/src
        files:
          - /exadel/src/docker-compose.yml
      register: output
