services:
  reverse-proxy:
    container_name: ngix
    image: giorgaaa/customnginx:latest
    ports:
      - "80:80"
    depends_on:
      - authservice
      - storageservice
  authservice:
    container_name: authservice
    image: giorgaaa/exportpro.authservice:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MongoDbDocker=${MongoDbDocker}
    ports:
      - "5000:8080"
     
  storageservice:
    container_name: storageservice
    image: giorgaaa/exportpro.storageservice:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MongoDbDocker=${MongoDbDocker}
    ports:
      - "1500:8080"
