services:
  mongodb:
    container_name: ExportProDb
    image: mongo
    ports:
    - "27017:27017"
    volumes:
     - /data/db    
  exportpro:
    container_name: ExportPro
    image: giorgaaa/exadel-export-pro:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MongoDbDocker=mongodb://ExportProDb:27017
    ports:
      - "100:8080"
      - "5000:8080"
    depends_on:
      - mongodb
