services:
  mongodb:
    container_name: ExportProDb
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - /data/db    

  authservice:
    container_name: authservice
    image: giorgaaa/exportpro.authservice:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MongoDbDocker=mongodb://ExportProDb:27017
    ports:
      - "5000:8080"
    depends_on:
      - mongodb
     
  storageservice:
    container_name: storageservice
    image: giorgaaa/exportpro.storageservice:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "1500:8080"
    depends_on:
      - authservice
