global:
  scrape_interval: 30s
  evaluation_interval: 25s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]  

  - job_name: 'dotnet-services'
    static_configs:
      - targets:
          - 'authservice:8080'      
          - 'storageservice:8080'  
          - 'exportservice:8080'    
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
